"""
Registry Renderer Core Logic
Migrated from tools/render_registry.py
"""
import yaml
import re
from pathlib import Path

REGISTRY_PATH = Path(r"C:\Users\kryst\Infrastructure\PROJECT_REGISTRY_MASTER.md")

def load_frontmatter(path):
    if not path.exists():
        print(f"Error: {path} not found.")
        return None, None
        
    content = path.read_text(encoding='utf-8')
    match = re.search(r'^---\s*\n(.*?)\n---\s*\n(.*)$', content, re.DOTALL)
    if not match:
        print("Error: No frontmatter found.")
        return None, content
        
    fm_text = match.group(1)
    body_text = match.group(2)
    
    try:
        data = yaml.safe_load(fm_text)
        return data, body_text
    except Exception as e:
        print(f"Error parsing YAML: {e}")
        return None, content

def render_tables(data):
    # 1. Entities Table
    entities_table = "| Canonical ID | Display Name | Kind | Role | Facets |\n"
    entities_table += "| :--- | :--- | :--- | :--- | :--- |\n"
    
    encoded_entities = data.get('entities', [])
    # Sort by Kind then ID
    encoded_entities.sort(key=lambda x: (x.get('kind', 'z'), x.get('canonical_id', '')))
    
    for ent in encoded_entities:
        c_id = f"`{ent.get('canonical_id', '')}`"
        name = f"**{ent.get('display_name', '')}**"
        kind = f"`{ent.get('kind', '')}`"
        role = ent.get('role', '')
        
        facets = []
        if 'facets' in ent:
            for f_name, f_data in ent['facets'].items():
                if f_name == 'repo':
                    facets.append('`repo`')
                elif f_name == 'agent_persona':
                    facets.append('`agent`')
                else:
                    facets.append(f"`{f_name}`")
        facets_str = ", ".join(facets)
        
        entities_table += f"| {c_id} | {name} | {kind} | {role} | {facets_str} |\n"

    # 2. Projects Table
    projects_table = "| Project ID | Repo | Local Path | Status |\n"
    projects_table += "| :--- | :--- | :--- | :--- |\n"
    
    encoded_projects = data.get('projects', [])
    encoded_projects.sort(key=lambda x: x.get('project_id', ''))
    
    for proj in encoded_projects:
        p_id = f"`{proj.get('project_id', '')}`"
        repo = proj.get('repo', {}).get('url') or '-'
        if isinstance(repo, str) and repo.startswith('http'):
            # simple link format
            pass
            
        paths = proj.get('local_paths', [])
        path_str = f"`{paths[0]}`" if paths else "-"
        status = proj.get('status', '').title()
        
        projects_table += f"| {p_id} | {repo} | {path_str} | {status} |\n"
        
    # 3. Locations Table (New!)
    locations_table = "| Location ID | Kind | Path | Description |\n"
    locations_table += "| :--- | :--- | :--- | :--- |\n"
    
    encoded_locs = data.get('locations', [])
    for loc in encoded_locs:
        l_id = f"`{loc.get('location_id', '')}`"
        kind = f"`{loc.get('kind', '')}`"
        path = f"`{loc.get('local_path', '')}`"
        desc = loc.get('description', '')
        
        locations_table += f"| {l_id} | {kind} | {path} | {desc} |\n"

    return entities_table, projects_table, locations_table

def regenerate_registry(path=REGISTRY_PATH):
    print(f"Rendering Registry: {path}")
    data, _ = load_frontmatter(path)
    if not data: return
    
    fm_str = yaml.dump(data, sort_keys=False, width=1000)
    
    ent_tbl, proj_tbl, loc_tbl = render_tables(data)
    
    new_content = f"""---
{fm_str}---

# Infrastructure Project Registry — Master (V2)

**Master registry for SERAPHINA Federation.**
*Source of Truth: YAML Frontmatter (above)*
*Updated: 2025-12-16*

## 1. Entities (Identity & Facets)
*Autogenerated from Frontmatter*

{ent_tbl}

## 2. Projects (Repositories)
*Autogenerated from Frontmatter*

{proj_tbl}

## 3. Locations (Roots)
*Autogenerated from Frontmatter*

{loc_tbl}
"""
    path.write_text(new_content, encoding='utf-8')
    print(f"Updated {path}")
